- new command-event redirection for built-in newLISP server! no longer need to prepend ? when running built-in server - new command-event handler also handles GET parameters appeneded to the request the way apache QSA redirection does! - updated multiplication value for newlisp symbol size from 32 to proper 28 value - removed all use of ? prepending to URLs

diff --git a/example-site/newlispServer b/example-site/newlispServer
--- a/example-site/newlispServer
+++ b/example-site/newlispServer
@@ -1,4 +1,11 @@
 #!/bin/bash
 
+NEWLISP_REDIRECTION="./dragonfly-framework/newlisp-redirection.lsp"
+
+if [ ! -f $NEWLISP_REDIRECTION ] ; then
+	echo "ERROR: cannot find file: $NEWLISP_REDIRECTION"
+	exit 1
+fi
+
 echo "If all goes well visit http://localhost:8080 in your browser"
-newlisp -http -d 8080 -w .
+newlisp "$NEWLISP_REDIRECTION" -c -http -d 8080 -w . $*
